apiVersion: apps/v1
kind: Deployment
metadata:
  name: projetnodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projetnodejs
  template:
    metadata:
      labels:
        app: projetnodejs
    spec:
      containers:
      - name: projetnodejs
        image: projetnodejs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
