apiVersion: v1
kind: Service
metadata:
  name: projetnodejs-service
spec:
  type: NodePort
  selector:
    app: projetnodejs
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081 